"use client";

import { useState } from "react";
import { FiCheckCircle, FiChevronDown, FiClock, FiMapPin, FiPackage, FiShield, FiTruck } from "react-icons/fi";
import type { IconType } from "react-icons";

const process = [
  { number: "01", title: "Reservation & Payment", text: "Your unit is reserved and prepared as soon as payment is confirmed." },
  { number: "02", title: "Confirmed Delivery", text: "Our team verifies the order and coordinates the shipment." },
  { number: "03", title: "Tracking Information", text: "You receive shipment details as your order moves through delivery." },
];
const deliverySteps = ["Confirm Your Order", "Parts Preparation", "Shipment", "Delivery"];
const deliveryExpectations: { title: string; text: string; icon: IconType }[] = [
  { title: "Shipping Time", text: "Most orders ship within 5–7 business days.", icon: FiClock },
  { title: "Freight Delivery", text: "Large parts ship by freight with tracking.", icon: FiTruck },
  { title: "Delivery Location", text: "Ship to your home, shop, or approved location.", icon: FiMapPin },
  { title: "Inspection At Delivery", text: "Inspect the package before signing the delivery receipt.", icon: FiPackage },
  { title: "Safe Handling", text: "Parts are packed and transported with care.", icon: FiShield },
  { title: "Professional Service", text: "Contact our support team if you need assistance.", icon: FiCheckCircle },
];
const exclusions = ["Improper installation", "Modifications or alterations of any kind", "Labor or installation costs", "Damage caused by abuse or neglect", "Incorrect fitment or misuse", "Damage caused by failure to follow manufacturer recommendations"];
const questions = ["How do I place an order?", "Do you ship nationwide?", "Can I pick up parts in person?", "What's included with a used engine?", "Can you ship to a business address?", "Can you ship to a residential address?", "What if my order is damaged, incorrect, or defective?", "Do you offer a warranty on used engines & transmissions?", "What if my engine or transmission fails?"];

const ShippingWarrantyContent = () => {
  const [openQuestion, setOpenQuestion] = useState<number | null>(0);
  return <>
    <section className="bg-white px-5 py-16 sm:py-20"><div className="container mx-auto max-w-6xl text-center"><p className="font-['Barlow_Condensed'] text-sm font-bold uppercase tracking-[0.18em] text-green-600">Shipping Made Simple</p><h2 className="mt-3 font-['Barlow_Condensed'] text-4xl font-extrabold uppercase leading-none text-slate-900 sm:text-5xl">We Ship Replacement Parts Across <span className="text-green-600">The USA</span></h2><p className="mt-4 text-slate-600">Your order is handled carefully from the moment it is confirmed to the moment it arrives.</p><div className="mt-10 grid gap-4 md:grid-cols-3">{process.map((item) => <article key={item.number} className="rounded-lg border border-slate-200 bg-white p-6 text-left shadow-sm"><span className="font-['Barlow_Condensed'] text-3xl font-extrabold text-green-600">{item.number}</span><h3 className="mt-3 font-['Barlow_Condensed'] text-xl font-bold uppercase text-slate-900">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.text}</p></article>)}</div></div></section>
    <section className="bg-slate-50 px-5 py-16 sm:py-20"><div className="container mx-auto max-w-6xl text-center"><p className="font-['Barlow_Condensed'] text-sm font-bold uppercase tracking-[0.18em] text-green-600">Our Shipping Process</p><h2 className="mt-3 font-['Barlow_Condensed'] text-4xl font-extrabold uppercase leading-none text-slate-900 sm:text-5xl">From Order To Delivery In <span className="text-green-600">4 Simple Steps</span></h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{deliverySteps.map((step, index) => <article key={step} className="rounded-xl bg-white p-6 text-left shadow-sm"><span className="font-['Barlow_Condensed'] text-3xl font-extrabold text-green-600">0{index + 1}</span><h3 className="mt-3 font-['Barlow_Condensed'] text-xl font-bold uppercase text-slate-900">{step}</h3><p className="mt-2 text-sm leading-6 text-slate-600">We keep the process clear and send updates as your order progresses.</p></article>)}</div></div></section>
    <section className="bg-[#f4f8f4] px-5 py-16 sm:py-20"><div className="container mx-auto max-w-6xl text-center"><p className="font-['Barlow_Condensed'] text-sm font-bold uppercase tracking-[0.18em] text-green-600">Shipping Details</p><h2 className="mt-3 font-['Barlow_Condensed'] text-4xl font-extrabold uppercase leading-none text-slate-900 sm:text-5xl">What To Expect With <span className="text-green-600">Your Delivery</span></h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{deliveryExpectations.map(({ title, text, icon: Icon }) => <article key={title} className="rounded-xl border border-slate-200 bg-white p-6 text-left"><span className="flex size-11 items-center justify-center rounded-xl bg-green-100 text-green-700"><Icon aria-hidden className="size-5" /></span><h3 className="mt-4 font-['Barlow_Condensed'] text-xl font-bold uppercase text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="bg-white px-5 py-16 sm:py-20"><div className="container mx-auto max-w-5xl text-center"><p className="font-['Barlow_Condensed'] text-sm font-bold uppercase tracking-[0.18em] text-green-600">Warranty Terms</p><h2 className="mt-3 font-['Barlow_Condensed'] text-4xl font-extrabold uppercase leading-none text-slate-900 sm:text-5xl">Know What Is <span className="text-green-600">Not Covered</span></h2><div className="mt-8 grid gap-x-8 gap-y-3 rounded-xl border border-slate-200 p-6 text-left sm:grid-cols-2">{exclusions.map((item) => <p key={item} className="flex gap-2 text-sm leading-6 text-slate-600"><FiCheckCircle aria-hidden className="mt-1 size-4 shrink-0 text-green-600" />{item}</p>)}</div><p className="mt-5 text-xs text-slate-500">Warranty exclusions vary by product. Refer to the warranty documentation associated with your order.</p></div></section>
    <section className="bg-slate-50 px-5 py-16 sm:py-20"><div className="container mx-auto max-w-4xl"><div className="text-center"><p className="font-['Barlow_Condensed'] text-sm font-bold uppercase tracking-[0.18em] text-green-600">Need Help?</p><h2 className="mt-3 font-['Barlow_Condensed'] text-4xl font-extrabold uppercase leading-none text-slate-900 sm:text-5xl">Questions, <span className="text-green-600">Answered</span></h2></div><div className="mt-10 space-y-3">{questions.map((question, index) => { const isOpen = openQuestion === index; return <div key={question} className="rounded-xl border border-slate-200 bg-white"><button type="button" aria-expanded={isOpen} onClick={() => setOpenQuestion(isOpen ? null : index)} className="flex min-h-14 w-full items-center justify-between gap-4 px-5 text-left font-['Barlow_Condensed'] text-lg font-bold uppercase text-slate-900 focus-visible:outline focus-visible:outline-4 focus-visible:outline-offset-2 focus-visible:outline-green-300"><span>{question}</span><FiChevronDown aria-hidden className={`size-5 shrink-0 text-green-600 transition-transform ${isOpen ? "rotate-180" : ""}`} /></button>{isOpen && <p className="border-t border-slate-100 px-5 py-4 text-sm leading-6 text-slate-600">Our parts specialists can walk you through the details for your order. Contact us with your vehicle and order information for the fastest answer.</p>}</div>; })}</div></div></section>
  </>;
};

export default ShippingWarrantyContent;
